apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: document-server
  namespace: thinkcloudly-lab
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-cluster-issuer"
    kubernetes.io/ingress.class: "nginx"
spec:
  # ingressClassName: nginx
  tls:
  - hosts:
    - backend.thinkbizly.com
    secretName: backend-tls-prod
  rules:
  - host: backend.thinkbizly.com
    http:
      paths:
        - pathType: Prefix
          path: "/document-server/"
          backend:
            service:
              name: document-server
              port:
                number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: document-server
  namespace: thinkcloudly-lab
spec:
  type: ClusterIP
  selector:
    app: document-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-server
  namespace: thinkcloudly-lab
  labels:
    app: document-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: document-server
  template:
    metadata:
      labels:
        app: document-server
    spec:
      containers:
      - name: document-server
        image: "654202376781.dkr.ecr.us-east-1.amazonaws.com/document-server:latest"
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
        - name: GOOGLE_SERVICE_ACCOUNT_EMAIL
          valueFrom:
            secretKeyRef:
              name: gcp-credentials
              key: GOOGLE_SERVICE_ACCOUNT_EMAIL
        - name: GOOGLE_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: gcp-credentials
              key: GOOGLE_PRIVATE_KEY

        - name: GOOGLE_SCOPE1
          valueFrom:
            secretKeyRef:
              name: gcp-credentials
              key: GOOGLE_SCOPE1